name: Build and deploy to GHPages
on:
  push:
    branches:
      - Web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: scripts/build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: www
