name: Build and deploy to GHPages
on:
  push:
    branches:
      - Web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install python2.7 cmake default-jre git-core &&
          git clone https://github.com/emscripten-core/emsdk.git &&
          cd emsdk &&
          ./emsdk install latest &&
          ./emsdk activate latest

      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          source ./emsdk/emsdk_env.sh &&
          ./scripts/build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: www
