name: Build and deploy to GHPages
on:
  push:
    branches:
      - Web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v5
        with:
          # Make sure to set a version number!
          version: latest
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'

      - name: Verify emcc
        run: emcc -v

      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: ./scripts/build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: www
